module.exports = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Overview",
      items: [
        { type: "doc", id: "overview/project-overview", label: "Project Overview" },
        { type: "doc", id: "overview/tech-stack", label: "Tech Stack" },
        { type: "doc", id: "overview/folder-structure", label: "Folder Structure" },
      ],
    },
    {
      type: "category",
      label: "Alur Bisnis",
      items: [
        { type: "doc", id: "business-flow/purchases", label: "Pembelian" },
        { type: "doc", id: "business-flow/production", label: "Produksi" },
        { type: "doc", id: "business-flow/sales", label: "Penjualan" },
        { type: "doc", id: "business-flow/stock-flow", label: "Alur Stok" },
      ],
    },
    {
      type: "category",
      label: "Logika Sistem",
      items: [
        { type: "doc", id: "system-logic/stock-rules", label: "Aturan Stok" },
        { type: "doc", id: "system-logic/variant-logic", label: "Logika Varian" },
        { type: "doc", id: "system-logic/costing-hpp", label: "Costing dan HPP" },
        { type: "doc", id: "system-logic/sales-status", label: "Status Penjualan" },
        { type: "doc", id: "system-logic/production-rules", label: "Aturan Produksi" },
        { type: "doc", id: "system-logic/reset-test-data", label: "Reset Data Uji" },
      ],
    },
    {
      type: "category",
      label: "Dokumentasi Menu",
      items: [
        { type: "doc", id: "menus/dashboard", label: "Dashboard" },
        { type: "doc", id: "menus/master-data", label: "Master Data" },
        { type: "doc", id: "menus/raw-materials", label: "Bahan Baku" },
        { type: "doc", id: "menus/products", label: "Produk Jadi" },
        { type: "doc", id: "menus/pricing-rules", label: "Aturan Harga" },
        { type: "doc", id: "menus/inventory-stock-management", label: "Manajemen Stok" },
        { type: "doc", id: "menus/inventory-stock-adjustment", label: "Penyesuaian Stok" },
        { type: "doc", id: "menus/production", label: "Menu Produksi" },
        { type: "doc", id: "menus/semi-finished", label: "Bahan Setengah Jadi" },
        { type: "doc", id: "menus/purchases", label: "Pembelian" },
        { type: "doc", id: "menus/sales", label: "Penjualan" },
        { type: "doc", id: "menus/reports", label: "Laporan" },
      ],
    },
    {
      type: "category",
      label: "Detail Produksi",
      items: [
        { type: "doc", id: "production-detail/overview", label: "Overview Produksi" },
        { type: "doc", id: "production-detail/steps", label: "Tahapan Produksi" },
        { type: "doc", id: "production-detail/profiles", label: "Profil Produksi" },
        { type: "doc", id: "production-detail/semi-finished", label: "Bahan Setengah Jadi" },
        { type: "doc", id: "production-detail/boms", label: "BOM Produksi" },
        { type: "doc", id: "production-detail/orders", label: "Order Produksi" },
        { type: "doc", id: "production-detail/work-logs", label: "Work Log Produksi" },
        { type: "doc", id: "production-detail/payroll", label: "Payroll Produksi" },
        { type: "doc", id: "production-detail/hpp-analysis", label: "Analisis HPP" },
        { type: "doc", id: "production-detail/field-reference", label: "Referensi Field" },
        { type: "doc", id: "production-detail/status-transitions", label: "Status & Transisi" },
        { type: "doc", id: "production-detail/action-flows", label: "Alur Aksi" },
        { type: "doc", id: "production-detail/known-issues-production", label: "Known Issues Produksi" },
        { type: "doc", id: "production-detail/validation-checklist-production", label: "Checklist Validasi" },
      ],
    },
    {
      type: "category",
      label: "Testing Center",
      items: [
        { type: "doc", id: "testing-center/overview", label: "Overview Testing" },
        { type: "doc", id: "testing-center/master-data", label: "Checklist Master Data" },
        { type: "doc", id: "testing-center/inventory", label: "Checklist Inventory" },
        { type: "doc", id: "testing-center/production", label: "Checklist Produksi" },
        { type: "doc", id: "testing-center/transactions", label: "Checklist Transaksi" },
        { type: "doc", id: "testing-center/reports", label: "Checklist Laporan" },
        { type: "doc", id: "testing-center/uat", label: "UAT Final" },
        { type: "doc", id: "testing-center/regression-log", label: "Regression Log" },
      ],
    },
    {
      type: "category",
      label: "Maintenance",
      items: [
        { type: "doc", id: "maintenance/change-log", label: "Change Log" },
        { type: "doc", id: "maintenance/bug-fix-log", label: "Bug Fix Log" },
        { type: "doc", id: "maintenance/improvements", label: "Improvements" },
        { type: "doc", id: "maintenance/known-issues", label: "Known Issues" },
        { type: "doc", id: "maintenance/checklist-validasi", label: "Checklist Validasi" },
        { type: "doc", id: "maintenance/roadmap", label: "Roadmap" },
      ],
    },
  ],
};
