module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Overview',
      items: [
        { type: 'doc', id: 'overview/project-overview', label: 'Project Overview' },
        { type: 'doc', id: 'overview/tech-stack', label: 'Tech Stack' },
        { type: 'doc', id: 'overview/folder-structure', label: 'Folder Structure' },
      ],
    },
    {
      type: 'category',
      label: 'Business Flow',
      items: [
        { type: 'doc', id: 'business-flow/purchases', label: 'Purchases' },
        { type: 'doc', id: 'business-flow/production', label: 'Production' },
        { type: 'doc', id: 'business-flow/sales', label: 'Sales' },
        { type: 'doc', id: 'business-flow/stock-flow', label: 'Stock Flow' },
      ],
    },
    {
      type: 'category',
      label: 'System Logic',
      items: [
        { type: 'doc', id: 'system-logic/stock-rules', label: 'Stock Rules' },
        { type: 'doc', id: 'system-logic/variant-logic', label: 'Variant Logic' },
        { type: 'doc', id: 'system-logic/costing-hpp', label: 'Costing dan HPP' },
        { type: 'doc', id: 'system-logic/sales-status', label: 'Sales Status' },
        { type: 'doc', id: 'system-logic/production-rules', label: 'Production Rules' },
        { type: 'doc', id: 'system-logic/reset-test-data', label: 'Reset Test Data' },
      ],
    },
    {
      type: 'category',
      label: 'Menu Guide',
      items: [
        { type: 'doc', id: 'menus/dashboard', label: 'Dashboard' },
        {
          type: 'category',
          label: 'Master Data',
          items: [
            { type: 'doc', id: 'menus/master-data', label: 'Overview Master Data' },
            { type: 'doc', id: 'menus/products', label: 'Produk Jadi' },
            { type: 'doc', id: 'menus/raw-materials', label: 'Bahan Baku' },
            { type: 'doc', id: 'menus/categories', label: 'Kategori' },
            { type: 'doc', id: 'menus/suppliers', label: 'Supplier' },
            { type: 'doc', id: 'menus/customers', label: 'Pelanggan' },
            { type: 'doc', id: 'menus/pricing-rules', label: 'Pricing Rules' },
          ],
        },
        {
          type: 'category',
          label: 'Inventory',
          items: [
            { type: 'doc', id: 'menus/inventory', label: 'Overview Inventory' },
            { type: 'doc', id: 'menus/inventory-stock-management', label: 'Manajemen Stok' },
            { type: 'doc', id: 'menus/inventory-stock-adjustment', label: 'Penyesuaian Stok' },
          ],
        },
        {
          type: 'category',
          label: 'Produksi',
          items: [
            { type: 'doc', id: 'menus/production', label: 'Overview Produksi' },
            { type: 'doc', id: 'production-detail/steps', label: 'Tahapan Produksi' },
            { type: 'doc', id: 'production-detail/employees', label: 'Karyawan Produksi' },
            { type: 'doc', id: 'production-detail/profiles', label: 'Profil Produksi' },
            { type: 'doc', id: 'production-detail/semi-finished', label: 'Semi Finished Materials' },
            { type: 'doc', id: 'production-detail/boms', label: 'BOM Produksi' },
            { type: 'doc', id: 'production-detail/orders', label: 'Production Orders' },
            { type: 'doc', id: 'production-detail/work-logs', label: 'Work Log Produksi' },
            { type: 'doc', id: 'production-detail/payroll', label: 'Payroll Produksi' },
            { type: 'doc', id: 'production-detail/hpp-analysis', label: 'Analisis HPP' },
          ],
        },
        {
          type: 'category',
          label: 'Transaksi',
          items: [
            { type: 'doc', id: 'menus/transactions', label: 'Overview Transaksi' },
            { type: 'doc', id: 'menus/purchases', label: 'Pembelian' },
            { type: 'doc', id: 'menus/sales', label: 'Penjualan' },
            { type: 'doc', id: 'menus/returns', label: 'Retur' },
          ],
        },
        {
          type: 'category',
          label: 'Kas & Biaya',
          items: [
            { type: 'doc', id: 'menus/finance-reports', label: 'Overview Kas & Biaya' },
            { type: 'doc', id: 'menus/cash-in', label: 'Pemasukan' },
            { type: 'doc', id: 'menus/cash-out', label: 'Pengeluaran' },
          ],
        },
        {
          type: 'category',
          label: 'Laporan',
          items: [
            { type: 'doc', id: 'menus/reports', label: 'Overview Laporan' },
            { type: 'doc', id: 'menus/stock-report', label: 'Laporan Stok' },
            { type: 'doc', id: 'menus/purchases-report', label: 'Laporan Pembelian' },
            { type: 'doc', id: 'menus/sales-report', label: 'Laporan Penjualan' },
            { type: 'doc', id: 'menus/profit-loss', label: 'Laba Rugi' },
          ],
        },
        {
          type: 'category',
          label: 'Utilities',
          items: [
            { type: 'doc', id: 'menus/reset-test-data', label: 'Reset Data Uji' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Production Detail',
      items: [
        { type: 'doc', id: 'production-detail/overview', label: 'Overview Produksi' },
        { type: 'doc', id: 'production-detail/steps', label: 'Tahapan Produksi' },
        { type: 'doc', id: 'production-detail/employees', label: 'Karyawan Produksi' },
        { type: 'doc', id: 'production-detail/profiles', label: 'Profil Produksi' },
        { type: 'doc', id: 'production-detail/semi-finished', label: 'Semi Finished Materials' },
        { type: 'doc', id: 'production-detail/boms', label: 'BOM Produksi' },
        { type: 'doc', id: 'production-detail/orders', label: 'Production Orders' },
        { type: 'doc', id: 'production-detail/work-logs', label: 'Work Log Produksi' },
        { type: 'doc', id: 'production-detail/payroll', label: 'Payroll Produksi' },
        { type: 'doc', id: 'production-detail/hpp-analysis', label: 'Analisis HPP' },
        { type: 'doc', id: 'production-detail/field-reference', label: 'Referensi Field' },
        { type: 'doc', id: 'production-detail/status-transitions', label: 'Status & Transisi' },
        { type: 'doc', id: 'production-detail/action-flows', label: 'Alur Aksi' },
        { type: 'doc', id: 'production-detail/known-issues-production', label: 'Known Issues Produksi' },
        { type: 'doc', id: 'production-detail/validation-checklist-production', label: 'Checklist Validasi' },
      ],
    },
    {
      type: 'category',
      label: 'Testing Center',
      items: [
        { type: 'doc', id: 'testing-center/overview', label: 'Overview Testing' },
        { type: 'doc', id: 'testing-center/master-data', label: 'Checklist Master Data' },
        { type: 'doc', id: 'testing-center/inventory', label: 'Checklist Inventory' },
        { type: 'doc', id: 'testing-center/production', label: 'Checklist Produksi' },
        { type: 'doc', id: 'testing-center/transactions', label: 'Checklist Transaksi' },
        { type: 'doc', id: 'testing-center/reports', label: 'Checklist Laporan' },
        { type: 'doc', id: 'testing-center/uat', label: 'UAT Final' },
        { type: 'doc', id: 'testing-center/regression-log', label: 'Regression Log' },
      ],
    },
    {
      type: 'category',
      label: 'Maintenance',
      items: [
        { type: 'doc', id: 'maintenance/change-log', label: 'Change Log' },
        { type: 'doc', id: 'maintenance/bug-fix-log', label: 'Bug Fix Log' },
        { type: 'doc', id: 'maintenance/known-issues', label: 'Known Issues' },
        { type: 'doc', id: 'maintenance/roadmap', label: 'Roadmap' },
        { type: 'doc', id: 'maintenance/checklist-validasi', label: 'Checklist Validasi' },
      ],
    },
  ],
};
