const BACKUP_FORMAT = "imsbackup";
const LEGACY_BACKUP_FORMAT = "imsbak";
const SUPPORTED_BACKUP_FORMATS = new Set([BACKUP_FORMAT, LEGACY_BACKUP_FORMAT]);
const BACKUP_FORMAT_VERSION = 2;
const BACKUP_FILE_SUFFIX = ".imsbackup";
const LEGACY_BACKUP_FILE_SUFFIX = ".imsbak.zip";
const SUPPORTED_BACKUP_FILE_SUFFIXES = [BACKUP_FILE_SUFFIX, LEGACY_BACKUP_FILE_SUFFIX];
const BACKUP_TYPES = new Set(["manual", "daily", "monthly", "pre-update", "pre-restore", "pre-reset", "pre-repair", "pre-import", "manual-import", "test"]);
const RESTORE_CONFIRM_KEYWORD = "RESTORE DATABASE";
const SQLITE_PACKAGE_DATABASE_FILE = "database.sqlite";
const SQLITE_PACKAGE_MANIFEST_FILE = "manifest.json";
const SQLITE_PACKAGE_CHECKSUM_FILE = "checksum.sha256";
const SQLITE_PACKAGE_README_FILE = "README_RESTORE.txt";
const ZIP_COMPRESSION_STORE = 0;
const ZIP_COMPRESSION_DEFLATE = 8;
const DAILY_RETENTION_DAYS = 60;
const MONTHLY_RETENTION_COUNT = 12;
const BACKUP_LIFECYCLE_INTERVAL_MS = 60 * 60 * 1000;
const BACKUP_DISK_RESERVE_BYTES = 128 * 1024 * 1024;
const ZIP32_MAX_ENTRY_BYTES = 0xffffffff;
const ZIP32_MAX_ENTRIES = 0xffff;

module.exports = {
  BACKUP_FILE_SUFFIX,
  BACKUP_FORMAT,
  BACKUP_FORMAT_VERSION,
  BACKUP_DISK_RESERVE_BYTES,
  BACKUP_LIFECYCLE_INTERVAL_MS,
  BACKUP_TYPES,
  DAILY_RETENTION_DAYS,
  LEGACY_BACKUP_FILE_SUFFIX,
  LEGACY_BACKUP_FORMAT,
  MONTHLY_RETENTION_COUNT,
  RESTORE_CONFIRM_KEYWORD,
  SQLITE_PACKAGE_CHECKSUM_FILE,
  SQLITE_PACKAGE_DATABASE_FILE,
  SQLITE_PACKAGE_MANIFEST_FILE,
  SQLITE_PACKAGE_README_FILE,
  SUPPORTED_BACKUP_FILE_SUFFIXES,
  SUPPORTED_BACKUP_FORMATS,
  ZIP_COMPRESSION_DEFLATE,
  ZIP_COMPRESSION_STORE,
  ZIP32_MAX_ENTRIES,
  ZIP32_MAX_ENTRY_BYTES,
};
