// =====================================================
// Page: Work Log Produksi
// Revisi:
// - bisa ambil data/template dari BOM
// - bisa ambil data/template dari Production Order
// - Produksi lebih fokus ke eksekusi, bukan planning dari nol
// =====================================================

import { useEffect, useMemo, useState } from "react";
import { buildCountSummary, createKeywordMatcher, matchFieldValue } from '../../utils/produksi/productionPageHelpers';
import { getWorkLogMaterialOptions, getWorkLogTargetOptions, toReferenceOptions } from '../../utils/produksi/productionReferenceHelpers';
import ProductionPageHeader from '../../components/Produksi/shared/ProductionPageHeader';
import SummaryStatGrid from '../../components/Layout/Display/SummaryStatGrid';
import ProductionFilterCard from '../../components/Produksi/shared/ProductionFilterCard';
import ProductionWorkLogDetailDrawer from './components/ProductionWorkLogDetailDrawer';
import EditableLineSection from '../../components/Produksi/shared/EditableLineSection';
import {
  Button,
  Card,
  Col,
  DatePicker,
  Divider,
  Drawer,
  Empty,
  Form,
  Input,
  InputNumber,
  message,
  Popconfirm,
  Row,
  Select,
  Space,
  Table,
  Tag,
  Typography,
} from "antd";
import {
  DeleteOutlined,
  EditOutlined,
  EyeOutlined,
} from "@ant-design/icons";
import dayjs from "dayjs";
import {
  DEFAULT_PRODUCTION_WORK_LOG_FORM,
  DEFAULT_WORK_LOG_MATERIAL_USAGE,
  DEFAULT_WORK_LOG_OUTPUT,
  PRODUCTION_WORK_LOG_SOURCE_TYPES,
  PRODUCTION_WORK_LOG_STATUSES,
  WORK_LOG_SOURCE_TYPE_MAP,
  WORK_LOG_STATUS_MAP,
  calculateProductionMonitoring,
} from "../../constants/productionWorkLogOptions";
import {
  buildWorkLogDraftFromBom,
  buildWorkLogDraftFromProductionOrder,
  completeProductionWorkLog,
  createProductionWorkLogFromOrder,
  getAllProductionWorkLogs,
  getWorkLogReferenceData,
  updateProductionWorkLog,
} from "../../services/Produksi/productionWorkLogsService";
import {
  generatePayrollLinesFromCompletedWorkLog,
  getAllProductionPayrolls,
} from "../../services/Produksi/productionPayrollsService";
import { DataRefreshIndicator, getDataTableEmptyText } from "../../components/Layout/Feedback/DataLoadingState";
import formatNumber, { parseIntegerIdInput } from "../../utils/formatters/numberId";
import formatCurrency from "../../utils/formatters/currencyId";
import { getFormArrayValue, removeArrayItemByIndex, upsertArrayItemByIndex } from "../../utils/forms/formArrayHelpers";
import { buildWorkLogMaterialUsageFormLine, buildWorkLogOutputFormLine } from "../../utils/produksi/productionLineBuilders";
import {
  buildProductionStepPayrollSnapshot,
} from "../../utils/produksi/productionPayrollRuleHelpers";
import { buildDisplayReferenceSearchText, resolveDisplayReference } from "../../utils/references/displayReferenceResolver";
import useAuth from "../../hooks/useAuth";
import WorkLogMaterialUsageModal from "./components/WorkLogMaterialUsageModal";
import WorkLogOutputModal from "./components/WorkLogOutputModal";
import WorkLogCompleteModal from "./components/WorkLogCompleteModal";
import {
  getWorkLogSourceTagColor,
  getWorkLogStatusTagColor,
  isEditableProductionWorkLog,
  renderCompleteWorkLogEstimateInfo,
  renderWorkLogCellBlock,
  workLogUiClassNames,
} from './helpers/productionWorkLogsPageHelpers';

// IMS NOTE [AKTIF/GUARDED] - Standar input angka bulat
// Fungsi blok: mengarahkan InputNumber aktif ke step 1, precision 0, dan parser integer Indonesia.
// Hubungan flow: hanya membatasi input/display UI; service calculation stok, kas, HPP, payroll, dan report tidak diubah.
// Alasan logic: IMS operasional memakai angka tanpa desimal, sementara data lama decimal tidak dimigrasi otomatis.
// Behavior: input baru no-decimal; business rules dan schema Firestore tetap sama.

const getProductionPayrollsForWorkLogDisplaySafely = async () => {
  try {
    return await getAllProductionPayrolls();
  } catch (error) {
    console.error("Gagal memuat payroll untuk display detail Work Log", error);
    return [];
  }
};

const ProductionWorkLogs = () => {
  const { profile, firebaseUser } = useAuth();

  // =====================================================
  // IMS NOTE [AKTIF/GUARDED] - Actor audit Work Log.
  // Fungsi blok: mengirim user login ke service update/complete/payroll agar audit tidak jatuh ke "system".
  // Hubungan flow: hanya metadata createdBy/updatedBy/autoGeneratedBy; posting stok, payroll idempotency, HPP, dan lifecycle PO tidak diubah.
  // Alasan logic: Work Log completed sudah menyimpan operator produksi, tetapi actor aplikasi tetap perlu tercatat dari Auth session.
  // =====================================================
  const currentUser = useMemo(() => ({
    email: profile?.email || firebaseUser?.email || "",
    displayName: profile?.displayName || profile?.name || firebaseUser?.displayName || "",
    uid: profile?.authUid || profile?.uid || profile?.id || firebaseUser?.uid || "",
  }), [firebaseUser, profile]);

  // SECTION: state utama
  const [loading, setLoading] = useState(false);
  const [workLogs, setWorkLogs] = useState([]);
  const [productionPayrolls, setProductionPayrolls] = useState([]);
  const [referenceData, setReferenceData] = useState({
    boms: [],
    productionOrders: [],
    employees: [],
    rawMaterials: [],
    semiFinishedMaterials: [],
    products: [],
    productionSteps: [],
    productionProfiles: [],
  });

  // SECTION: state filter
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");

  // SECTION: state form
  const [formVisible, setFormVisible] = useState(false);
  const [detailVisible, setDetailVisible] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const [selectedRecord, setSelectedRecord] = useState(null);
  const [editingRecord, setEditingRecord] = useState(null);

  // SECTION: modal line
  const [materialModalVisible, setMaterialModalVisible] = useState(false);
  const [outputModalVisible, setOutputModalVisible] = useState(false);
  const [editingMaterialIndex, setEditingMaterialIndex] = useState(null);
  const [editingOutputIndex, setEditingOutputIndex] = useState(null);
  const [completeModalVisible, setCompleteModalVisible] = useState(false);
  const [completingRecord, setCompletingRecord] = useState(null);

  // SECTION: form instances
  const [form] = Form.useForm();
  const [materialForm] = Form.useForm();
  const [outputForm] = Form.useForm();
  const [completeForm] = Form.useForm();

  // SECTION: watch source
  const targetTypeValue = Form.useWatch("targetType", form);
  const targetIdValue = Form.useWatch("targetId", form);
  const stepIdValue = Form.useWatch("stepId", form);
  const productionProfileIdValue = Form.useWatch("productionProfileId", form);
  const goodQtyValue = Form.useWatch("goodQty", form);
  const baseInputQtyValue = Form.useWatch("baseInputQty", form);
  const leftoverLeafQtyValue = Form.useWatch("leftoverLeafQty", form);
  const leftoverStemQtyValue = Form.useWatch("leftoverStemQty", form);
  const leftoverPetalFlowerEquivalentValue = Form.useWatch("leftoverPetalFlowerEquivalent", form);

  const loadData = async () => {
    try {
      setLoading(true);
      const [workLogResult, refResult, payrollResult] = await Promise.all([
        getAllProductionWorkLogs(),
        getWorkLogReferenceData(),
        getProductionPayrollsForWorkLogDisplaySafely(),
      ]);

      setWorkLogs(workLogResult);
      setProductionPayrolls(Array.isArray(payrollResult) ? payrollResult : []);
      setReferenceData(refResult);

      if (Array.isArray(refResult?.metaWarnings) && refResult.metaWarnings.length > 0) {
        message.warning(refResult.metaWarnings[0]);
      }
    } catch (error) {
      console.error(error);
      message.error("Gagal memuat work log produksi");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);


  const summary = useMemo(() => {
    return buildCountSummary(workLogs, {
      completed: (item) => item.status === "completed",
      inProgress: (item) => item.status === "in_progress",
    });
  }, [workLogs]);

  // =====================================================
  // AKTIF UI-ONLY - Summary Work Log PO-first.
  // Fungsi blok:
  // - menampilkan KPI utama Work Log dengan pola SummaryStatGrid yang lebih compact dan konsisten;
  // - tidak menampilkan Cancelled sebagai KPI utama karena cancel bukan action aktif di halaman Work Log.
  // Hubungan flow:
  // - hanya presentasi data count; tidak mengubah status, service, stok, payroll, HPP, atau lifecycle PO.
  // =====================================================
  const summaryItems = useMemo(() => [
    {
      key: "total",
      title: "Total Work Log",
      value: formatNumber(summary.total || 0),
      subtitle: "Realisasi produksi yang tercatat",
      columns: { xs: 24, md: 8 },
    },
    {
      key: "progress",
      title: "Sedang Produksi",
      value: formatNumber(summary.inProgress || 0),
      subtitle: "Belum selesai / belum posting output",
      columns: { xs: 24, md: 8 },
    },
    {
      key: "completed",
      title: "Selesai",
      value: formatNumber(summary.completed || 0),
      subtitle: "Output sudah diproses ke flow selesai",
      columns: { xs: 24, md: 8 },
    },
  ], [summary.completed, summary.inProgress, summary.total]);

  const filteredData = useMemo(() => {
    return workLogs.filter((item) => {
      const matchSearch = createKeywordMatcher(
        {
          ...item,
          displayReference: buildDisplayReferenceSearchText(item, { fields: ["workNumber", "productionOrderCode"] }),
        },
        ["workNumber", "productionOrderCode", "displayReference", "targetName", "stepName"],
        search,
      );

      const matchStatus = matchFieldValue(item, statusFilter, "status");

      return matchSearch && matchStatus;
    });
  }, [workLogs, search, statusFilter]);

  const resetFormState = () => {
    setEditingRecord(null);
    form.resetFields();
    form.setFieldsValue({
      ...DEFAULT_PRODUCTION_WORK_LOG_FORM,
      workDate: dayjs(),
      sourceType: "production_order",
      status: "in_progress",
      materialUsages: [],
      outputs: [],
      workerIds: [],
      productionOrderId: undefined,
      productionProfileId: undefined,
    });
  };

  // =====================================================
  // Handler edit work log
  // Catatan:
  // - drawer form masih dipakai untuk mode edit data Work Log existing
  // - Work Log baru dibuat dari action Mulai Produksi di Production Order, bukan tombol tambah manual di halaman ini
  // =====================================================
  const handleEdit = (record) => {
    if (!isEditableProductionWorkLog(record)) {
      message.warning("Work Log yang sudah completed tidak bisa diedit dari UI utama.");
      return;
    }

    setEditingRecord(record);
    form.setFieldsValue({
      ...DEFAULT_PRODUCTION_WORK_LOG_FORM,
      ...record,
      workDate: record.workDate
        ? dayjs(record.workDate?.toDate?.() || record.workDate)
        : null,
    });
    setFormVisible(true);
  };

  const handleViewDetail = (record) => {
    setSelectedRecord(record);
    setDetailVisible(true);
  };

  // =====================================================
  // Helper options
  // =====================================================
  const productionOrderOptions = toReferenceOptions(
    referenceData.productionOrders || [],
  );

  const employeeOptions = toReferenceOptions(referenceData.employees || []);

  const stepOptions = toReferenceOptions(referenceData.productionSteps || []);

  const getTargetOptions = (targetType) =>
    getWorkLogTargetOptions(referenceData, targetType);

  const getProductionProfileOptions = (targetId) =>
    (referenceData.productionProfiles || [])
      .filter((item) => item.productId === targetId)
      .map((item) => ({
        value: item.id,
        label: `${item.profileName || '-'}${item.isDefault !== false ? ' (Default)' : ''}`,
      }));

  const getMaterialOptions = (itemType) =>
    getWorkLogMaterialOptions(referenceData, itemType);


  const selectedProductionProfile = useMemo(
    () =>
      (referenceData.productionProfiles || []).find(
        (item) => item.id === productionProfileIdValue,
      ) || null,
    [referenceData.productionProfiles, productionProfileIdValue],
  );

  const selectedStepForMonitoring = useMemo(
    () =>
      (referenceData.productionSteps || []).find(
        (item) => item.id === stepIdValue,
      ) || null,
    [referenceData.productionSteps, stepIdValue],
  );

  const monitoringPreview = useMemo(
    () =>
      calculateProductionMonitoring(
        {
          ...(selectedProductionProfile || {}),
          basisType: selectedStepForMonitoring?.basisType || '',
          referenceYieldPerBaseQty:
            selectedStepForMonitoring?.basisType === 'per_meter'
              ? (selectedStepForMonitoring?.name || '').toLowerCase().includes('daun')
                ? selectedProductionProfile?.leafYieldPerMeter
                : selectedProductionProfile?.petalYieldPerMeter
              : selectedStepForMonitoring?.basisType === 'per_rod_40cm'
                ? selectedProductionProfile?.stemYieldPerRod40cm
                : 0,
          flowerEquivalentPerBaseQty:
            selectedStepForMonitoring?.basisType === 'per_meter'
              ? (selectedStepForMonitoring?.name || '').toLowerCase().includes('daun')
                ? selectedProductionProfile?.flowerEquivalentPerLeafMeter
                : selectedProductionProfile?.flowerEquivalentPerPetalMeter
              : selectedStepForMonitoring?.basisType === 'per_rod_40cm'
                ? selectedProductionProfile?.flowerEquivalentPerRod40cm
                : 0,
          batchLeafQty:
            (selectedProductionProfile?.assemblyLeafPackCount || 0) *
            (selectedProductionProfile?.leafYieldPerMeter || 0),
          batchStemQty: selectedProductionProfile?.assemblyStemQty || 0,
        },
        {
          basisType: selectedStepForMonitoring?.basisType || '',
          baseInputQty: baseInputQtyValue,
          goodQty: goodQtyValue,
          leftoverLeafQty: leftoverLeafQtyValue,
          leftoverStemQty: leftoverStemQtyValue,
          leftoverPetalFlowerEquivalent: leftoverPetalFlowerEquivalentValue,
        },
      ),
    [
      selectedProductionProfile,
      selectedStepForMonitoring,
      baseInputQtyValue,
      goodQtyValue,
      leftoverLeafQtyValue,
      leftoverStemQtyValue,
      leftoverPetalFlowerEquivalentValue,
    ],
  );

  /* =====================================================
  SECTION: Apply BOM Template To Work Log — LEGACY-COMPAT/GUARDED
  Fungsi:
  - Mengisi form Work Log dari BOM sebagai template eksekusi, bukan membuat status Draft baru.

  Dipakai oleh:
  - Tombol Ambil Data BOM di drawer Work Log.

  Alasan perubahan:
  - Nama helper service lama tetap kompatibel (`buildWorkLogDraftFromBom`), tetapi UI aktif tidak lagi memakai konsep Draft Work Log.

  Catatan cleanup:
  - Nama helper service bisa dirapikan pada refactor non-fungsional terpisah.

  Risiko:
  - Jika status form ikut dikembalikan ke Draft, flow produksi bisa melewati start/in_progress yang dipakai PO dan stok.
  ===================================================== */
  const handleApplyBomTemplate = (bomId) => {
    const bom = (referenceData.boms || []).find((item) => item.id === bomId);

    if (!bom) {
      message.error("BOM tidak ditemukan");
      return;
    }

    const templateValues = buildWorkLogDraftFromBom(bom);

    form.setFieldsValue({
      ...form.getFieldsValue(),
      ...templateValues,
      status: "in_progress",
    });

    message.success("Data BOM berhasil dimasukkan ke Work Log");
  };

  /* =====================================================
  SECTION: Apply Production Order Template To Work Log — LEGACY-COMPAT/GUARDED
  Fungsi:
  - Mengisi form Work Log dari Production Order sebagai template eksekusi, bukan membuat status Draft baru.

  Dipakai oleh:
  - Tombol Ambil Data PO dan perubahan pilihan Production Order di drawer Work Log.

  Alasan perubahan:
  - Helper service `buildWorkLogDraftFromProductionOrder` tetap dipertahankan demi kompatibilitas, tetapi label dan status UI aktif tidak lagi Draft.

  Catatan cleanup:
  - Nama helper service bisa dirapikan pada batch refactor setelah flow produksi stabil.

  Risiko:
  - Jika data PO diterapkan dengan status Draft, Work Log baru bisa tidak sesuai lifecycle eksekusi dan status PO.
  ===================================================== */
  const handleApplyProductionOrderTemplate = async (orderId) => {
    try {
      const productionOrder = (referenceData.productionOrders || []).find(
        (item) => item.id === orderId,
      );

      if (!productionOrder) {
        message.error("Production order tidak ditemukan");
        return;
      }

      const templateValues = await buildWorkLogDraftFromProductionOrder(productionOrder);

      form.setFieldsValue({
        ...form.getFieldsValue(),
        ...templateValues,
        sourceType: "production_order",
        status: "in_progress",
      });

      message.success("Data Order Produksi berhasil dimasukkan ke Work Log");
    } catch (error) {
      console.error(error);
      message.error(error?.message || "Gagal mengambil data PO");
    }
  };

  // =====================================================
  // Modal material usage
  // =====================================================
  const openMaterialModal = (index = null, record = null) => {
    setEditingMaterialIndex(index);
    materialForm.setFieldsValue(
      record
        ? { ...DEFAULT_WORK_LOG_MATERIAL_USAGE, ...record }
        : DEFAULT_WORK_LOG_MATERIAL_USAGE,
    );
    setMaterialModalVisible(true);
  };

  // =====================================================
  // Modal output
  // =====================================================
  const openOutputModal = (index = null, record = null) => {
    setEditingOutputIndex(index);
    outputForm.setFieldsValue(
      record
        ? { ...DEFAULT_WORK_LOG_OUTPUT, ...record }
        : DEFAULT_WORK_LOG_OUTPUT,
    );
    setOutputModalVisible(true);
  };

  const handleSaveMaterialUsage = async () => {
    try {
      const values = await materialForm.validateFields();
      const options = getMaterialOptions(values.itemType);
      const selected = options.find(
        (item) => item.value === values.itemId,
      )?.raw;

      const line = buildWorkLogMaterialUsageFormLine({
        values,
        selectedItem: selected,
      });

      const current = getFormArrayValue(form, "materialUsages");
      const next = upsertArrayItemByIndex(
        current,
        editingMaterialIndex,
        line,
      );

      form.setFieldValue("materialUsages", next);
      setMaterialModalVisible(false);
      setEditingMaterialIndex(null);
      materialForm.resetFields();
    } catch (error) {
      if (error?.errorFields) return;
      console.error(error);
      message.error("Gagal menyimpan material usage");
    }
  };

  const handleRemoveMaterialUsage = (index) => {
    const current = getFormArrayValue(form, "materialUsages");
    form.setFieldValue(
      "materialUsages",
      removeArrayItemByIndex(current, index),
    );
  };

  const handleSaveOutput = async () => {
    try {
      const values = await outputForm.validateFields();

      const options =
        values.outputType === "semi_finished_material"
          ? (referenceData.semiFinishedMaterials || []).map((item) => ({
              value: item.id,
              raw: item,
            }))
          : (referenceData.products || []).map((item) => ({
              value: item.id,
              raw: item,
            }));

      const selected = options.find(
        (item) => item.value === values.outputIdRef,
      )?.raw;

      const line = buildWorkLogOutputFormLine({
        values: {
          ...values,
          rejectQty: 0,
          reworkQty: 0,
        },
        selectedOutput: selected,
      });

      const current = getFormArrayValue(form, "outputs");
      const next = upsertArrayItemByIndex(
        current,
        editingOutputIndex,
        line,
      );

      form.setFieldValue("outputs", next);
      setOutputModalVisible(false);
      setEditingOutputIndex(null);
      outputForm.resetFields();
    } catch (error) {
      if (error?.errorFields) return;
      console.error(error);
      message.error("Gagal menyimpan output");
    }
  };

  const handleRemoveOutput = (index) => {
    const current = getFormArrayValue(form, "outputs");
    form.setFieldValue(
      "outputs",
      removeArrayItemByIndex(current, index),
    );
  };

  // =====================================================
  // Submit work log
  // Jika sourceType = production_order dan belum ada editing record,
  // create langsung dari order agar status PO ikut in_production
  // =====================================================
  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      const selectedTarget = getTargetOptions(values.targetType).find(
        (item) => item.value === values.targetId,
      )?.raw;

      const selectedStep = (referenceData.productionSteps || []).find(
        (item) => item.id === values.stepId,
      );

      const selectedEmployees = (referenceData.employees || []).filter((item) =>
        (values.workerIds || []).includes(item.id),
      );

      const selectedProfile = (referenceData.productionProfiles || []).find(
        (item) => item.id === values.productionProfileId,
      );

      const selectedStepPayrollSnapshot = selectedStep
        ? buildProductionStepPayrollSnapshot(selectedStep)
        : null;

      const payload = {
        ...values,
        workDate: values.workDate ? values.workDate.toDate() : null,
        targetCode: selectedTarget?.code || "",
        targetName: selectedTarget?.name || "",
        targetUnit: selectedTarget?.unit || values.targetUnit || "pcs",
        productionProfileName: selectedProfile?.profileName || '',
        productionProfile: {
          ...(selectedProfile || {}),
          basisType: selectedStep?.basisType || '',
          referenceYieldPerBaseQty:
            selectedStep?.basisType === 'per_meter'
              ? (selectedStep?.name || '').toLowerCase().includes('daun')
                ? selectedProfile?.leafYieldPerMeter
                : selectedProfile?.petalYieldPerMeter
              : selectedStep?.basisType === 'per_rod_40cm'
                ? selectedProfile?.stemYieldPerRod40cm
                : 0,
          flowerEquivalentPerBaseQty:
            selectedStep?.basisType === 'per_meter'
              ? (selectedStep?.name || '').toLowerCase().includes('daun')
                ? selectedProfile?.flowerEquivalentPerLeafMeter
                : selectedProfile?.flowerEquivalentPerPetalMeter
              : selectedStep?.basisType === 'per_rod_40cm'
                ? selectedProfile?.flowerEquivalentPerRod40cm
                : 0,
          batchLeafQty:
            (selectedProfile?.assemblyLeafPackCount || 0) *
            (selectedProfile?.leafYieldPerMeter || 0),
          batchStemQty: selectedProfile?.assemblyStemQty || 0,
        },
        stepCode: selectedStep?.code || "",
        stepName: selectedStep?.name || "",
        sequenceNo: values.sequenceNo || 1,
        ...(selectedStepPayrollSnapshot
          ? {
              stepPayrollMode: selectedStepPayrollSnapshot.payrollMode,
              stepPayrollRate: selectedStepPayrollSnapshot.payrollRate,
              stepPayrollQtyBase: selectedStepPayrollSnapshot.payrollQtyBase,
              stepPayrollOutputBasis: selectedStepPayrollSnapshot.payrollOutputBasis,
              stepPayrollClassification: selectedStepPayrollSnapshot.payrollClassification,
              stepPayrollIncludeInHpp: selectedStepPayrollSnapshot.includePayrollInHpp,
              stepPayrollRuleSource: "production_step",
            }
          : {}),
        workerCodes: selectedEmployees.map((item) => item.code || ""),
        workerNames: selectedEmployees.map((item) => item.name || ""),
        workerCount: selectedEmployees.length,
      };

      setSubmitting(true);

      if (editingRecord?.id) {
        await updateProductionWorkLog(editingRecord.id, payload, currentUser);
        message.success("Work log produksi berhasil diperbarui");
      } else if (
        payload.sourceType === "production_order" &&
        payload.productionOrderId
      ) {
        await createProductionWorkLogFromOrder(
          payload.productionOrderId,
          payload,
          currentUser,
        );
        message.success("Work log dari Order Produksi berhasil dibuat");
      } else {
        message.error("Work Log baru harus dimulai dari Order Produksi melalui tombol Mulai Produksi.");
        return;
      }

      setFormVisible(false);
      resetFormState();
      await loadData();
    } catch (error) {
      if (error?.errorFields) return;

      if (error?.type === "validation" && error?.errors) {
        const normalFields = [];
        const globalMessages = [];

        Object.entries(error.errors).forEach(([name, errors]) => {
          if (["materialUsages", "outputs"].includes(name)) {
            globalMessages.push(errors);
          } else {
            normalFields.push({
              name,
              errors: [errors],
            });
          }
        });

        if (normalFields.length > 0) {
          form.setFields(normalFields);
        }

        if (globalMessages.length > 0) {
          message.error(globalMessages[0]);
        }
        return;
      }

      console.error(error);
      message.error(error?.message || "Gagal menyimpan work log produksi");
    } finally {
      setSubmitting(false);
    }
  };

  // =====================================================
  // Popup selesai produksi
  // Catatan maintainability:
  // - User isi Good Qty, operator, dan catatan dari popup ini; field hasil selain good hanya compatibility data lama.
  // - Setelah update work log, baru service complete menambah stok output dan menutup PO
  // =====================================================
  const handleOpenComplete = (record) => {
    setCompletingRecord(record);
    completeForm.setFieldsValue({
      goodQty: record.goodQty || 0,
      workerIds: Array.isArray(record.workerIds) ? record.workerIds : [],
      notes: record.notes || '',
    });
    setCompleteModalVisible(true);
  };

  const handleMarkCompleted = async () => {
    try {
      const values = await completeForm.validateFields();
      if (!completingRecord?.id) return;

      await updateProductionWorkLog(
        completingRecord.id,
        {
          ...completingRecord,
          goodQty: values.goodQty,
          rejectQty: 0,
          reworkQty: 0,
          scrapQty: 0,
          workerIds: values.workerIds || [],
          workerNames: (referenceData.employees || [])
            .filter((item) => (values.workerIds || []).includes(item.id))
            .map((item) => item.name || ''),
          workerCodes: (referenceData.employees || [])
            .filter((item) => (values.workerIds || []).includes(item.id))
            .map((item) => item.code || ''),
          workerCount: Array.isArray(values.workerIds) ? values.workerIds.length : 0,
          notes: values.notes || '',
        },
        currentUser,
      );

      await completeProductionWorkLog(completingRecord.id, currentUser);
      // =====================================================
      // ACTIVE / GUARDED - auto payroll setelah Work Log selesai
      // Fungsi blok:
      // - membuat payroll line otomatis dari Work Log completed;
      // - menjaga flow lama output stok tetap selesai dulu, lalu payroll dibuat dengan guard idempotent.
      // Alasan blok ini dipakai:
      // - regression sebelumnya Work Log selesai tetapi Payroll Produksi tetap kosong.
      // Status:
      // - aktif dipakai; bukan legacy dan tidak mengubah business rule stok/HPP.
      // =====================================================
      let payrollMessageHandled = false;
      try {
        const payrollResult = await generatePayrollLinesFromCompletedWorkLog(completingRecord.id, currentUser);
        const createdPayrollCount = Number(payrollResult?.createdCount || 0);
        const skippedPayrollCount = Number(payrollResult?.skippedCount || 0);

        if (createdPayrollCount > 0) {
          payrollMessageHandled = true;
          message.success(`Work log selesai dan ${createdPayrollCount} line payroll dibuat.`);
        } else if (skippedPayrollCount > 0) {
          payrollMessageHandled = true;
          message.info('Work log selesai. Payroll sudah pernah dibuat, tidak dibuat dobel.');
        }
      } catch (payrollError) {
        // =====================================================
        // ACTIVE / GUARDED - fallback error payroll setelah complete
        // Fungsi blok:
        // - menjaga user tahu bahwa Work Log sudah selesai meski auto payroll gagal;
        // - tidak menjalankan ulang complete agar output stok tidak dobel.
        // Alasan blok ini dipakai:
        // - complete Work Log adalah guarded stock flow, sedangkan payroll bisa diperbaiki via task terpisah/manual.
        // Status:
        // - aktif sebagai guard; bukan legacy.
        // =====================================================
        console.error(payrollError);
        payrollMessageHandled = true;
        message.warning(payrollError?.message || 'Work log selesai, tetapi payroll otomatis gagal dibuat.');
      }

      if (!payrollMessageHandled) {
        message.success('Work log selesai. Output ditambahkan dan PO ditutup.');
      }
      setCompleteModalVisible(false);
      setCompletingRecord(null);
      completeForm.resetFields();
      await loadData();
    } catch (error) {
      if (error?.errorFields) return;
      console.error(error);
      message.error(error?.message || 'Gagal menyelesaikan work log');
    }
  };


  // =====================================================
  // Helper presentasi daftar & form Work Log
  // Catatan maintainability:
  // - Helper di bawah hanya untuk kebutuhan tampilan / readability UI.
  // - Jangan dipakai untuk mengubah logika transaksi, stok, atau status produksi.
  // - Tujuannya agar tampilan work log tetap rapi, profesional, dan mudah diaudit.
  // =====================================================
  const formatDisplayDate = (value, format = "DD/MM/YYYY") => {
    const rawValue = value?.toDate ? value.toDate() : value;
    return rawValue ? dayjs(rawValue).format(format) : "-";
  };

  // =====================================================
  // Kolom list Work Log Produksi
  // Fungsi blok:
  // - menampilkan work log aktif dalam tabel utama yang ringkas;
  // - menjaga tombol Detail/Edit/Selesaikan langsung terlihat tanpa scroll horizontal.
  // Alasan perubahan:
  // - regression UI sebelumnya memakai scroll x besar dan fixed action sehingga aksi terdorong ke kanan.
  // Status:
  // - aktif dipakai; handler aksi tetap sama dan tidak mengubah flow produksi.
  // =====================================================
  const columns = [
    {
      title: "No. Work Log",
      dataIndex: "workNumber",
      key: "workNumber",
      width: 105,
      render: (value) => (
        <Typography.Text strong>{resolveDisplayReference({ workNumber: value }, { fields: ["workNumber"], fallback: "-" })}</Typography.Text>
      ),
    },
    {
      title: "Tanggal",
      dataIndex: "workDate",
      key: "workDate",
      width: 130,
      render: (value) => formatDisplayDate(value),
    },
    {
      title: "Target / Tahapan",
      key: "targetStep",
      width: 240,
      render: (_, record) => (
        renderWorkLogCellBlock(record.targetName || "-", [
          record.stepName || "-",
          record.targetVariantLabel ? `Varian: ${record.targetVariantLabel}` : null,
          `No. Order: ${record.productionOrderCode || "-"}`,
        ])
      ),
    },
    {
      title: "Qty",
      key: "qty",
      width: 130,
      render: (_, record) => (
        <Space direction="vertical" size={0}>
          <Typography.Text>Batch: {formatNumber(record.plannedQty)}</Typography.Text>
          <Typography.Text type="secondary">Estimasi: {formatNumber(record.theoreticalOutputQty || 0)}</Typography.Text>
          <Typography.Text type="secondary">Hasil baik: {formatNumber(record.goodQty)}</Typography.Text>
        </Space>
      ),
    },
    {
      title: "Biaya Aktual",
      dataIndex: "totalCostActual",
      key: "totalCostActual",
      width: 95,
      render: (value) => formatCurrency(value),
    },
    {
      title: "Sumber",
      dataIndex: "sourceType",
      key: "sourceType",
      width: 105,
      render: (value) => (
        <Tag className="ims-status-tag" color={getWorkLogSourceTagColor(value)}>
          {WORK_LOG_SOURCE_TYPE_MAP[value] || value || "-"}
        </Tag>
      ),
    },
    {
      title: "Status",
      dataIndex: "status",
      key: "status",
      width: 120,
      render: (value) => (
        <Tag className="ims-status-tag" color={getWorkLogStatusTagColor(value)}>
          {WORK_LOG_STATUS_MAP[value] || "-"}
        </Tag>
      ),
    },
    {
      title: "Aksi",
      key: "actions",
      width: 160,
      render: (_, record) => (
        // Aktif dipakai: tombol aksi disusun vertical compact agar tidak butuh scroll kanan.
        <Space direction="vertical" size={6} className="ims-action-group ims-action-group--vertical">
          <Button
            className="ims-action-button"
            size="small"
            icon={<EyeOutlined />}
            onClick={() => handleViewDetail(record)}
          >
            Detail
          </Button>

          {isEditableProductionWorkLog(record) && (
            <Button
              className="ims-action-button"
              size="small"
              icon={<EditOutlined />}
              onClick={() => handleEdit(record)}
            >
              Edit
            </Button>
          )}

          {isEditableProductionWorkLog(record) && (
            <Button
              className="ims-action-button"
              size="small"
              type="primary"
              onClick={() => handleOpenComplete(record)}
            >
              Selesaikan
            </Button>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div className="ims-page">
      <ProductionPageHeader
        title="Work Log Produksi"
        description="Realisasi kerja produksi dari order produksi. Work Log baru dibuat lewat tombol Mulai Produksi di menu Order Produksi."
      />

      <SummaryStatGrid
        items={summaryItems}
        className="ims-summary-row"
        gutter={[16, 16]}
      />

      <ProductionFilterCard>
          <Col xs={24} md={12}>
            <Input
              placeholder="Cari nomor, target, tahapan, PO..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              allowClear
            />
          </Col>

          <Col xs={24} md={12}>
            <Select
              className="ims-filter-control"
              value={statusFilter}
              onChange={setStatusFilter}
              options={[
                { value: "all", label: "Semua Status" },
                ...PRODUCTION_WORK_LOG_STATUSES,
              ]}
            />
          </Col>
      </ProductionFilterCard>

      <Card className="ims-section-card">
        {/* Aktif dipakai: scroll x besar dihapus agar aksi Work Log terlihat pada desktop/laptop normal. */}
        <DataRefreshIndicator loading={loading} dataSource={filteredData} />
        <Table
          className="ims-table"
          rowKey="id"
          columns={columns}
          dataSource={filteredData}
          locale={{
            emptyText: getDataTableEmptyText(loading, <Empty description="Belum ada data work log produksi" />),
          }}
          pagination={{
            pageSize: 10,
            showSizeChanger: true,
          }}
        />
      </Card>

      <Drawer
        title={
          editingRecord?.id
            ? "Edit Work Log Produksi"
            : "Work Log dari Order Produksi"
        }
        open={formVisible}
        onClose={() => {
          setFormVisible(false);
          resetFormState();
        }}
        width={980}
        destroyOnClose
        extra={
          <Space>
            <Button
              onClick={() => {
                setFormVisible(false);
                resetFormState();
              }}
            >
              Batal
            </Button>
            <Button type="primary" loading={submitting} onClick={handleSubmit}>
              Simpan
            </Button>
          </Space>
        }
      >
        <Form
          form={form}
          layout="vertical"
          initialValues={{
            ...DEFAULT_PRODUCTION_WORK_LOG_FORM,
            workDate: dayjs(),
            sourceType: "production_order",
            status: "in_progress",
          }}
        >
          <Divider orientation="left">Informasi Dasar</Divider>

          <Row gutter={16}>
            <Col xs={24} md={8}>
              <Form.Item
                label="No. Work Log"
                name="workNumber"
              >
                <Input placeholder="Otomatis: JOB-DDMMYYYY-001" disabled />
              </Form.Item>
            </Col>

            <Col xs={24} md={8}>
              <Form.Item
                label="Tanggal"
                name="workDate"
                rules={[{ required: true, message: "Tanggal wajib diisi" }]}
              >
                <DatePicker style={{ width: "100%" }} format="DD/MM/YYYY" />
              </Form.Item>
            </Col>

            <Col xs={24} md={8}>
              <Form.Item
                label="Sumber Work Log"
                name="sourceType"
                tooltip="Work Log baru dibuat dari order produksi. Manual/Planned hanya pembacaan data lama."
              >
                <Select options={PRODUCTION_WORK_LOG_SOURCE_TYPES} disabled />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item shouldUpdate noStyle>
            {({ getFieldValue }) => {
              const sourceType = getFieldValue("sourceType");

              return (
                <>
                  {sourceType === "production_order" ? (
                    <Card size="small" style={{ marginBottom: 16 }}>
                      <Row gutter={16}>
                        <Col xs={24} md={18}>
                          <Form.Item
                            label="No. Order Produksi"
                            name="productionOrderId"
                          >
                            <Select
                              showSearch
                              optionFilterProp="label"
                              options={productionOrderOptions}
                              placeholder="Pilih order produksi..."
                              disabled={Boolean(editingRecord?.id)}
                              onChange={(value) => {
                                if (value) {
                                  handleApplyProductionOrderTemplate(value);
                                }
                              }}
                            />
                          </Form.Item>
                        </Col>

                        <Col xs={24} md={6}>
                          <Form.Item label=" ">
                            <Button
                              block
                              disabled={Boolean(editingRecord?.id)}
                              onClick={() => {
                                const orderId =
                                  form.getFieldValue("productionOrderId");
                                if (orderId) {
                                  handleApplyProductionOrderTemplate(orderId);
                                }
                              }}
                            >
                              Ambil Data PO
                            </Button>
                          </Form.Item>
                        </Col>
                      </Row>
                    </Card>
                  ) : null}

                  {sourceType === "planned" ? (
                    <Card size="small" style={{ marginBottom: 16 }}>
                      <Row gutter={16}>
                        <Col xs={24} md={18}>
                          <Form.Item label="Resep Produksi" name="bomId">
                            <Select
                              showSearch
                              optionFilterProp="label"
                              options={(referenceData.boms || []).map(
                                (item) => ({
                                  value: item.id,
                                  label: item.name || "-",
                                }),
                              )}
                              placeholder="Pilih resep produksi..."
                            />
                          </Form.Item>
                        </Col>

                        <Col xs={24} md={6}>
                          <Form.Item label=" ">
                            <Button
                              block
                              onClick={() => {
                                const bomId = form.getFieldValue("bomId");
                                if (bomId) {
                                  handleApplyBomTemplate(bomId);
                                }
                              }}
                            >
                              Ambil Data BOM
                            </Button>
                          </Form.Item>
                        </Col>
                      </Row>
                    </Card>
                  ) : null}
                </>
              );
            }}
          </Form.Item>

          <Divider orientation="left">Target & Tahapan</Divider>

          <Row gutter={16}>
            <Col xs={24} md={8}>
              <Form.Item
                label="Jenis Target"
                name="targetType"
                rules={[
                  { required: true, message: "Jenis target wajib dipilih" },
                ]}
              >
                <Select
                  options={[
                    { value: "semi_finished_material", label: "Bahan Produksi" },
                    { value: "product", label: "Produk Jadi" },
                  ]}
                />
              </Form.Item>
            </Col>

            <Col xs={24} md={16}>
              <Form.Item
                label="Target Produksi"
                name="targetId"
                rules={[
                  { required: true, message: "Target produksi wajib dipilih" },
                ]}
              >
                <Select
                  showSearch
                  optionFilterProp="label"
                  options={getTargetOptions(targetTypeValue)}
                  placeholder="Pilih target produksi..."
                />
              </Form.Item>
            </Col>

            <Col xs={24} md={24}>
              <Form.Item label="Profil Produksi" name="productionProfileId">
                <Select
                  showSearch
                  optionFilterProp="label"
                  options={getProductionProfileOptions(targetIdValue)}
                  placeholder="Pilih profil produksi untuk target ini..."
                />
              </Form.Item>
            </Col>

            <Col xs={24} md={16}>
              <Form.Item
                label="Tahapan Produksi"
                name="stepId"
                rules={[{ required: true, message: "Tahapan wajib dipilih" }]}
              >
                <Select
                  showSearch
                  optionFilterProp="label"
                  options={stepOptions}
                  placeholder="Pilih tahapan..."
                />
              </Form.Item>
            </Col>

            <Col xs={24} md={8}>
              <Form.Item label="Sequence No" name="sequenceNo">
                <InputNumber min={1} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: "100%" }} />
              </Form.Item>
            </Col>
          </Row>

          <Divider orientation="left">Qty & Operator</Divider>

          <Row gutter={16}>
            <Col xs={24} md={6}>
              <Form.Item
                label="Qty Batch"
                name="plannedQty"
                rules={[{ required: true, message: "Planned qty wajib diisi" }]}
              >
                <InputNumber min={1} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: "100%" }} />
              </Form.Item>
            </Col>

            <Col xs={24} md={6}>
              <Form.Item label="Qty Input Dasar" name="baseInputQty">
                <InputNumber min={0} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: '100%' }} />
              </Form.Item>
            </Col>

            <Col xs={24} md={6}>
              <Form.Item label="Sisa Daun Aktual" name="leftoverLeafQty">
                <InputNumber min={0} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: '100%' }} />
              </Form.Item>
            </Col>

            <Col xs={24} md={6}>
              <Form.Item label="Sisa Kawat Aktual" name="leftoverStemQty">
                <InputNumber min={0} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: '100%' }} />
              </Form.Item>
            </Col>

            <Col xs={24} md={6}>
              <Form.Item label="Good Qty" name="goodQty">
                <InputNumber min={0} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: "100%" }} />
              </Form.Item>
            </Col>
            <Form.Item name="rejectQty" hidden><InputNumber /></Form.Item>
            <Form.Item name="reworkQty" hidden><InputNumber /></Form.Item>

            <Col xs={24}>
              <Form.Item label="Worker" name="workerIds">
                <Select
                  mode="multiple"
                  showSearch
                  optionFilterProp="label"
                  options={employeeOptions}
                  placeholder="Pilih operator produksi..."
                />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item label="Sisa Setara Bunga Kelopak" name="leftoverPetalFlowerEquivalent">
                <InputNumber min={0} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
          </Row>

          {selectedProductionProfile ? (
            <Card size="small" style={{ marginBottom: 16 }}>
              <Row gutter={[16, 16]}>
                <Col xs={24} md={8}><strong>Profil:</strong> {selectedProductionProfile.profileName || '-'}</Col>
                <Col xs={24} md={8}><strong>Teoritis Bunga:</strong> {formatNumber(monitoringPreview.theoreticalFlowerEquivalent || 0)}</Col>
                <Col xs={24} md={8}><strong>Miss %:</strong> {formatNumber(monitoringPreview.missPercent || 0)}%</Col>
                <Col xs={24} md={8}><strong>Miss Kelopak:</strong> {formatNumber(monitoringPreview.missPetalQty || 0)} pcs</Col>
                <Col xs={24} md={8}><strong>Miss Daun:</strong> {formatNumber(monitoringPreview.missLeafQty || 0)} pcs</Col>
                <Col xs={24} md={8}><strong>Miss Kawat:</strong> {formatNumber(monitoringPreview.missStemQty || 0)} pcs</Col>
              </Row>
            </Card>
          ) : null}

          <EditableLineSection
            title="Material Usages"
            description={editingRecord?.productionOrderId ? "Material dari PO terkunci agar pemakaian stok dan audit tidak berubah." : undefined}
            addButtonText="Tambah Material Usage"
            onAdd={() => openMaterialModal()}
            showAddButton={!editingRecord?.productionOrderId}
            dataSource={form.getFieldValue("materialUsages") || []}
            emptyText="Belum ada material usage"
            columns={[
              {
                title: "Item",
                key: "item",
                // =====================================================
                // AKTIF / GUARDED:
                // - metadata code/variant memakai class token global agar warna netral konsisten light/dark.
                // - hanya perubahan presentational; tidak mengubah payload work log, status, payroll, atau HPP.
                // =====================================================
                render: (_, record) => (
                  <div>
                    <div className={workLogUiClassNames.title}>{record.itemName || "-"}</div>
                    {record.resolvedVariantLabel ? (
                      <div className="ims-cell-meta">
                        Varian: {record.resolvedVariantLabel}
                      </div>
                    ) : null}
                  </div>
                ),
              },
              {
                title: "Qty",
                key: "qty",
                width: 180,
                render: (_, record) => (
                  <Space direction="vertical" size={0}>
                    <Typography.Text>
                      Plan: {formatNumber(record.plannedQty)}
                    </Typography.Text>
                    <Typography.Text type="secondary">
                      Actual: {formatNumber(record.actualQty)}
                    </Typography.Text>
                  </Space>
                ),
              },
              {
                title: "Total Cost",
                dataIndex: "totalCostSnapshot",
                width: 150,
                render: (value) => formatCurrency(value),
              },
              {
                title: "Aksi",
                width: 140,
                render: (_, record, index) => (
                  editingRecord?.productionOrderId ? (
                    <Typography.Text type="secondary" className="ims-cell-meta">Terkunci dari PO</Typography.Text>
                  ) : (
                    <Space direction="vertical" size={6} className="ims-action-group ims-action-group--vertical">
                      <Button className="ims-action-button" size="small" onClick={() => openMaterialModal(index, record)}>
                        Edit
                      </Button>
                      <Popconfirm
                        title="Hapus material usage ini?"
                        onConfirm={() => handleRemoveMaterialUsage(index)}
                        okText="Ya"
                        cancelText="Batal"
                      >
                        <Button className="ims-action-button" size="small" danger icon={<DeleteOutlined />} />
                      </Popconfirm>
                    </Space>
                  )
                ),
              },
            ]}
          />

          <EditableLineSection
            title="Outputs"
            description={editingRecord?.productionOrderId ? "Output dari PO terkunci. Isi Good Qty dari modal Selesaikan agar stok/HPP tetap konsisten." : undefined}
            addButtonText="Tambah Output"
            onAdd={() => openOutputModal()}
            showAddButton={!editingRecord?.productionOrderId}
            dataSource={form.getFieldValue("outputs") || []}
            emptyText="Belum ada output"
            columns={[
              {
                title: "Output",
                key: "output",
                render: (_, record) => (
                  <div>
                    <div className={workLogUiClassNames.title}>{record.outputName || "-"}</div>
                    <div className="ims-cell-meta">{record.outputCode || "-"}</div>
                    {record.outputVariantLabel ? (
                      <div className="ims-cell-meta">
                        Varian: {record.outputVariantLabel}
                      </div>
                    ) : null}
                  </div>
                ),
              },
              {
                title: "Qty",
                key: "qty",
                width: 180,
                render: (_, record) => (
                  <Typography.Text>
                    Good: {formatNumber(record.goodQty)}
                  </Typography.Text>
                ),
              },
              {
                title: "Aksi",
                width: 140,
                render: (_, record, index) => (
                  editingRecord?.productionOrderId ? (
                    <Typography.Text type="secondary" className="ims-cell-meta">Terkunci dari PO</Typography.Text>
                  ) : (
                    <Space direction="vertical" size={6} className="ims-action-group ims-action-group--vertical">
                      <Button className="ims-action-button" size="small" onClick={() => openOutputModal(index, record)}>
                        Edit
                      </Button>
                      <Popconfirm
                        title="Hapus output ini?"
                        onConfirm={() => handleRemoveOutput(index)}
                        okText="Ya"
                        cancelText="Batal"
                      >
                        <Button className="ims-action-button" size="small" danger icon={<DeleteOutlined />} />
                      </Popconfirm>
                    </Space>
                  )
                ),
              },
            ]}
          />

          <Divider orientation="left">Biaya & Catatan</Divider>

          <Row gutter={16}>
            <Col xs={24} md={4}>
              <Form.Item
                label="Biaya Tenaga Kerja"
                name="laborCostActual"
                tooltip="Biaya tenaga kerja aktif dibaca dari Payroll Produksi; estimasi tahapan hanya info."
              >
                <InputNumber min={0} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: "100%" }} disabled />
              </Form.Item>
            </Col>

            <Col xs={24} md={4}>
              <Form.Item
                label="Biaya Overhead"
                name="overheadCostActual"
                tooltip="Overhead aktif berasal dari resep produksi untuk listrik/glue gun."
              >
                <InputNumber min={0} step={1} precision={0} parser={parseIntegerIdInput} style={{ width: "100%" }} disabled={Boolean(editingRecord?.productionOrderId)} />
              </Form.Item>
            </Col>

            <Form.Item name="scrapQty" hidden>
              <InputNumber />
            </Form.Item>

            <Col xs={24} md={16}>
              <Form.Item label="Catatan" name="notes">
                <Input.TextArea rows={2} placeholder="Catatan work log..." />
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Drawer>

      <ProductionWorkLogDetailDrawer
        open={detailVisible}
        onClose={() => setDetailVisible(false)}
        selectedRecord={selectedRecord}
        productionPayrolls={productionPayrolls}
        referenceData={referenceData}
      />

      <WorkLogMaterialUsageModal
        open={materialModalVisible}
        editingIndex={editingMaterialIndex}
        form={materialForm}
        materialOptionsResolver={getMaterialOptions}
        onCancel={() => {
          setMaterialModalVisible(false);
          setEditingMaterialIndex(null);
          materialForm.resetFields();
        }}
        onOk={handleSaveMaterialUsage}
      />

      <WorkLogOutputModal
        open={outputModalVisible}
        editingIndex={editingOutputIndex}
        form={outputForm}
        referenceData={referenceData}
        onCancel={() => {
          setOutputModalVisible(false);
          setEditingOutputIndex(null);
          outputForm.resetFields();
        }}
        onOk={handleSaveOutput}
      />

      <WorkLogCompleteModal
        open={completeModalVisible}
        form={completeForm}
        employeeOptions={employeeOptions}
        estimateInfo={renderCompleteWorkLogEstimateInfo(completingRecord)}
        onCancel={() => {
          setCompleteModalVisible(false);
          setCompletingRecord(null);
          completeForm.resetFields();
        }}
        onOk={handleMarkCompleted}
      />

    </div>
  );
};

export default ProductionWorkLogs;
